export interface StudyPlanLink {
  /** Display label shown in the UI */
  label: string;
  /** Full URL — opens in a new tab */
  url: string;
}

export interface StudyPlanDay {
  dayNumber: number;
  date: string;
  isoDate: string;
  phase: number;
  phaseName: string;
  section: "English" | "Math" | "Reading" | "All" | "Setup" | "Rest";
  topic: string;
  resource: string;
  /** Specific clickable resource links for this day's session */
  links?: readonly StudyPlanLink[];
  timeMinutes: number;
}

export const STUDY_PLAN: readonly StudyPlanDay[] = [
  // Phase 0: Setup (Day 1)
  {
    dayNumber: 1,
    date: "May 3",
    isoDate: "2026-05-03",
    phase: 0,
    phaseName: "Setup",
    section: "Setup",
    topic: "Register for June 13 ACT, verify FMS requirement, set up your study resources",
    resource: "act.org/register, Khan Academy, resources.md",
    links: [
      { label: "ACT Registration", url: "https://www.act.org/content/act/en/register-for-the-act.html" },
      { label: "Khan Academy", url: "https://www.khanacademy.org/" },
      { label: "ACT Test Dates", url: "https://act.org/content/act/en/products-and-services/the-act/registration/test-dates.html" },
    ],
    timeMinutes: 30,
  },

  // Phase 1: English Foundations + Math Foundations (Days 2–16)
  {
    dayNumber: 2,
    date: "May 4",
    isoDate: "2026-05-04",
    phase: 1,
    phaseName: "Foundations",
    section: "English",
    topic: "Comma rules — the single most tested grammar concept",
    resource: "Khan Academy Grammar → Commas",
    links: [
      { label: "KA: Commas & Apostrophes Unit", url: "https://www.khanacademy.org/humanities/grammar/punctuation-the-comma-and-the-apostrophe" },
      { label: "KA: Meet the Comma (video)", url: "https://www.khanacademy.org/humanities/grammar/punctuation-the-comma-and-the-apostrophe/introduction-to-commas/v/meet-the-comma-the-comma-punctuation-khan-academy" },
      { label: "KA: Meet the Comma (practice)", url: "https://www.khanacademy.org/humanities/grammar/punctuation-the-comma-and-the-apostrophe/introduction-to-commas/e/meet-the-comma" },
      { label: "KA: Grammar Guide — Punctuation", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:digital-sat-grammar-practice/x0d47bcec73eb6c4b:boundaries-punctuation/a/grammar-guide-punctuation" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 3,
    date: "May 5",
    isoDate: "2026-05-05",
    phase: 1,
    phaseName: "Foundations",
    section: "Math",
    topic: "Fractions, decimals, percentages — Start with 5 confidence-builder warm-ups, then foundational practice",
    resource: "Khan Academy Pre-Algebra",
    links: [
      { label: "KA: Fraction Arithmetic", url: "https://www.khanacademy.org/math/arithmetic/fraction-arithmetic" },
      { label: "KA: Rates & Percentages", url: "https://www.khanacademy.org/math/cc-sixth-grade-math/x0267d782:cc-6th-rates-and-percentages" },
      { label: "KA: Fractions, Decimals & Percents (practice)", url: "https://www.khanacademy.org/math/cc-sixth-grade-math/x0267d782:cc-6th-rates-and-percentages/x0267d782:equivalent-representations-of-percent-problems" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 4,
    date: "May 6",
    isoDate: "2026-05-06",
    phase: 1,
    phaseName: "Foundations",
    section: "English",
    topic: "Apostrophes & possessives (it's vs its, plural vs possessive)",
    resource: "Khan Academy → Apostrophes",
    links: [
      { label: "KA: Choosing Between its and it's (video)", url: "https://www.khanacademy.org/humanities/grammar/punctuation-the-comma-and-the-apostrophe/its-vs-its/v/choosing-between-its-and-its-the-apostrophe-punctuation-khan-academy" },
      { label: "KA: its vs it's (practice)", url: "https://www.khanacademy.org/humanities/grammar/punctuation-the-comma-and-the-apostrophe/its-vs-its/e/choosing-between-its-and-it-s" },
      { label: "KA: Introduction to the Possessive (video)", url: "https://www.khanacademy.org/humanities/grammar/punctuation-the-comma-and-the-apostrophe/introduction-to-the-possessive/v/introduction-to-the-possessive-the-apostrophe-punctuation-khan-academy" },
      { label: "KA: Grammar Guide — Plurals & Possessives", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:digital-sat-grammar-practice/x0d47bcec73eb6c4b:fss-plurals-and-possessives/a/fss-grammar-guide-plurals-and-possessives" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 5,
    date: "May 7",
    isoDate: "2026-05-07",
    phase: 1,
    phaseName: "Foundations",
    section: "Math",
    topic: "Ratios, proportions, rates — Start with 5 confidence-builder warm-ups, then high-frequency practice",
    resource: "Khan Academy → Ratios",
    links: [
      { label: "KA: Proportional Relationships", url: "https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-ratio-proportion" },
      { label: "KA: Writing & Solving Proportions", url: "https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-ratio-proportion/cc-7th-write-and-solve-proportions" },
      { label: "KA: Proportion Word Problems (practice)", url: "https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-ratio-proportion/cc-7th-write-and-solve-proportions/v/writing-proportions" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 6,
    date: "May 8",
    isoDate: "2026-05-08",
    phase: 1,
    phaseName: "Foundations",
    section: "English",
    topic: "Subject-verb agreement — tricky when prepositional phrases get in the way",
    resource: "section-strategies.md",
    links: [
      { label: "KA: Subject-Verb Agreement (video)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/subject-verb-agreement-and-pronoun-antecedent-agreement/v/subject-verb-agreement-syntax-khan-academy" },
      { label: "KA: Subject-Verb Agreement (practice)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/subject-verb-agreement-and-pronoun-antecedent-agreement/e/subject-verb-agreement" },
      { label: "KA: Grammar Guide — Subject-Verb Agreement", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:digital-sat-grammar-practice/x0d47bcec73eb6c4b:fss-sva/a/fss-grammar-guide-subject-verb-agreement" },
      { label: "KA: Subject-Verb Agreement (SAT-style practice)", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:digital-sat-grammar-practice/x0d47bcec73eb6c4b:fss-sva/e/subject-verb-agreement-practice" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 7,
    date: "May 9",
    isoDate: "2026-05-09",
    phase: 1,
    phaseName: "Foundations",
    section: "Math",
    topic: "Solving linear equations — Start with 5 confidence-builder warm-ups, then one-variable, two-step, word problems",
    resource: "Khan Academy → Algebra Basics",
    links: [
      { label: "KA: One-Step & Two-Step Equations", url: "https://www.khanacademy.org/math/pre-algebra/xb4832e56:one-step-and-two-step-equations-inequalities" },
      { label: "KA: Solving Equations & Inequalities", url: "https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:solve-equations-inequalities" },
      { label: "KA: Solving Equations (mastery practice)", url: "https://www.khanacademy.org/kmap/operations-and-algebraic-thinking-j/oat231-solving-equations-inequalities" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 8,
    date: "May 10",
    isoDate: "2026-05-10",
    phase: 1,
    phaseName: "Foundations",
    section: "Reading",
    topic: "Keep your reading sharp: 1 full timed passage (9 questions, 10 min) + review your answers",
    resource: "Old prep book or free online",
    links: [
      { label: "ACT: Reading Sample Questions", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/act-online-test-sample-questions.html" },
      { label: "ACT QuizMe", url: "https://quizme.act.org/" },
      { label: "Varsity Tutors: ACT Reading Practice", url: "https://cdn.varsitytutors.com/act_reading-practice-tests" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 9,
    date: "May 11",
    isoDate: "2026-05-11",
    phase: 1,
    phaseName: "Foundations",
    section: "Math",
    topic: "Desmos basics — Start with 5 confidence-builder warm-ups, then practice graphing equations, finding intersections, and using sliders",
    resource: "Acely ACT Desmos Guide, desmos.com/calculator",
    links: [
      { label: "Desmos Graphing Calculator", url: "https://www.desmos.com/calculator" },
      { label: "Acely: ACT Desmos Guide", url: "https://acely.com/act-prep/act-desmos-calculator" },
      { label: "Acely: Desmos Guide Library", url: "https://acely.ai/desmos-guide-library/" },
      { label: "ACT: Math Calculator How-To Videos", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/math-calculator-how-to-videos.html" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 10,
    date: "May 12",
    isoDate: "2026-05-12",
    phase: 1,
    phaseName: "Foundations",
    section: "English",
    topic: "Run-on sentences, fragments, semicolons + pronoun errors",
    resource: "Khan Academy → Sentence Structure, section-strategies.md",
    links: [
      { label: "KA: Recognizing Fragments (video)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/fragments-and-run-ons/v/recognizing-fragments-syntax-khan-academy" },
      { label: "KA: Fragments (practice)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/fragments-and-run-ons/e/recognizing-fragments" },
      { label: "KA: Run-ons & Comma Splices (video)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/fragments-and-run-ons/v/run-ons-and-comma-splices-syntax-khan-academy" },
      { label: "KA: Run-ons (practice)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/fragments-and-run-ons/e/recognizing-run-ons-and-comma-splices" },
      { label: "KA: Intro to Semicolons (video)", url: "https://www.khanacademy.org/humanities/grammar/punctuation-the-colon-semicolon-and-more/introduction-to-semicolons/v/introduction-to-the-semicolon-the-colon-and-semicolon-punctuation-khan-academy" },
      { label: "KA: Pronoun-Antecedent Agreement (video)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/subject-verb-agreement-and-pronoun-antecedent-agreement/v/pronoun-antecedent-agreement-syntax-khan-academy" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 11,
    date: "May 13",
    isoDate: "2026-05-13",
    phase: 1,
    phaseName: "Foundations",
    section: "Math",
    topic: "Backsolving & picking numbers — Start with 5 confidence-builder warm-ups, then practice plugging in answer choices and substituting simple values",
    resource: "section-strategies.md",
    links: [
      { label: "Magoosh: Backsolving (free lesson)", url: "https://act.magoosh.com/lessons/3472-math-strategy-backsolving" },
      { label: "Magoosh: Picking Numbers (free lesson)", url: "https://act.magoosh.com/lessons/6961-math-strategy-picking-numbers-part-i" },
      { label: "Achievable: Answer-Based Strategies", url: "https://www.achievable.me/exams/act/insights/solve-math-problems-faster-with-answer-based-strategies/" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 12,
    date: "May 14",
    isoDate: "2026-05-14",
    phase: 1,
    phaseName: "Foundations",
    section: "English",
    topic: "Parallelism + comparisons + wordiness & redundancy",
    resource: "section-strategies.md",
    links: [
      { label: "KA: Parallel Structure (video)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/dangling-modifiers-and-parallel-structure/v/parallel-structure-syntax-khan-academy" },
      { label: "KA: Parallel Structure (practice)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/dangling-modifiers-and-parallel-structure/e/parallel-structure" },
      { label: "KA: Writing Concision (video)", url: "https://www.khanacademy.org/test-prep/sat/sat-reading-writing-practice/new-sat-writing-grammar/v/writing-concision-video-lesson" },
      { label: "Purdue OWL: Eliminating Wordiness (exercise)", url: "https://owl.purdue.edu/owl_exercises/sentence_style/eliminating_wordiness_test/eliminating_wordiness_exercise_1.html" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 13,
    date: "May 15",
    isoDate: "2026-05-15",
    phase: 1,
    phaseName: "Foundations",
    section: "Math",
    topic: "Geometry formulas only — Start with 5 confidence-builder warm-ups, then area, perimeter, circumference, Pythagorean theorem",
    resource: "Khan Academy → Basic Geometry",
    links: [
      { label: "KA: Area and Perimeter", url: "https://www.khanacademy.org/math/basic-geo/basic-geo-area-and-perimeter" },
      { label: "KA: Area & Circumference of Circles (video)", url: "https://www.khanacademy.org/math/basic-geo/x7fa91416:circles-cylinders-cones-and-spheres/x7fa91416:area-and-circumference-of-circles/v/area-of-a-circle" },
      { label: "KA: Pythagorean Theorem", url: "https://www.khanacademy.org/math/basic-geo/basic-geometry-pythagorean-theorem/" },
      { label: "KA: Pythagorean Theorem — Find Side Lengths (practice)", url: "https://www.khanacademy.org/math/cc-eighth-grade-math/cc-8th-geometry/cc-8th-pythagorean-theorem/e/pythagorean_theorem_1" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 14,
    date: "May 16",
    isoDate: "2026-05-16",
    phase: 1,
    phaseName: "Foundations",
    section: "English",
    topic: "Modifier placement + rhetorical skills intro (transitions)",
    resource: "section-strategies.md",
    links: [
      { label: "KA: Dangling Modifiers (video)", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english/dangling-modifiers-and-parallel-structure/v/dangling-modifiers-syntax-khan-academy" },
      { label: "KA: Subject-Modifier Placement (guide)", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:digital-sat-grammar-practice/x0d47bcec73eb6c4b:fss-subject-modifier-placement/a/fss-grammar-guide-subject-modifier-placement" },
      { label: "KA: Subject-Modifier Placement (practice)", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:digital-sat-grammar-practice/x0d47bcec73eb6c4b:fss-subject-modifier-placement/e/fss-subject-modifier-placement-practice" },
      { label: "KA: Transitions Lesson", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:foundations-expression-of-ideas-and-standard-english-conventions/x0d47bcec73eb6c4b:transitions/a/transitions-lesson" },
      { label: "KA: Transitions (practice)", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:foundations-expression-of-ideas-and-standard-english-conventions/x0d47bcec73eb6c4b:transitions/e/transitions-foundations" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 15,
    date: "May 17",
    isoDate: "2026-05-17",
    phase: 1,
    phaseName: "Foundations",
    section: "Math",
    topic: "Exponent rules + order of operations — Start with 5 confidence-builder warm-ups",
    resource: "Khan Academy → Exponents",
    links: [
      { label: "KA: Exponents & Order of Operations", url: "https://www.khanacademy.org/math/pre-algebra/xb4832e56:exponents-intro-and-order-of-operations" },
      { label: "KA: Order of Operations (PEMDAS)", url: "https://www.khanacademy.org/math/pre-algebra/xb4832e56:exponents-intro-and-order-of-operations/xb4832e56:order-of-operations" },
      { label: "KA: Exponent Properties", url: "https://www.khanacademy.org/math/cc-eighth-grade-math/cc-8th-numbers-operations/cc-8th-exponent-properties" },
      { label: "KA: Order of Operations Review", url: "https://www.khanacademy.org/math/pre-algebra/xb4832e56:exponents-intro-and-order-of-operations/xb4832e56:more-on-order-of-operations/a/order-of-operations-review" },
    ],
    timeMinutes: 60,
  },
  {
    dayNumber: 16,
    date: "May 18",
    isoDate: "2026-05-18",
    phase: 1,
    phaseName: "Foundations",
    section: "All",
    topic: "Diagnostic checkpoint: 10-question mini-assessment (~3 English, ~4 Math, ~3 Reading) — measure your progress before Phase 2",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "ACT QuizMe", url: "https://quizme.act.org/" },
      { label: "ACT: Online Sample Questions", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/act-online-test-sample-questions.html" },
    ],
    timeMinutes: 45,
  },

  // Phase 2: Strategy + Timed Practice (Days 17–30)
  {
    dayNumber: 17,
    date: "May 19",
    isoDate: "2026-05-19",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "English",
    topic: "Rhetorical skills focus: transitions, add/delete, sentence ordering",
    resource: "section-strategies.md",
    links: [
      { label: "KA: Transitions Lesson (medium)", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:medium/x0d47bcec73eb6c4b:transitions-2/a/transitions-lesson" },
      { label: "SupertutorTV: ACT English #1 Secret Tip", url: "https://supertutortv.com/act/act-english-section-1-secret-tip/" },
      { label: "SupertutorTV: Must-Know ACT English Strategy", url: "https://supertutortv.com/act/must-know-act-english-strategy/" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 18,
    date: "May 20",
    isoDate: "2026-05-20",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "Math",
    topic: "Inequalities + coordinate geometry (slope, midpoint, distance) — Start with 5 warm-ups",
    resource: "Khan Academy → Inequalities, Coordinate Plane",
    links: [
      { label: "KA: Solving Equations & Inequalities", url: "https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:solve-equations-inequalities" },
      { label: "KA: Inequalities (systems & graphs)", url: "https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:inequalities-systems-graphs" },
      { label: "KA: Slope", url: "https://www.khanacademy.org/math/cc-eighth-grade-math/cc-8th-linear-equations-functions/8th-slope" },
      { label: "KA: Distance & Midpoints", url: "https://www.khanacademy.org/math/geometry/hs-geo-analytic-geometry/hs-geo-distance-and-midpoints" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 19,
    date: "May 21",
    isoDate: "2026-05-21",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "English",
    topic: "Full timed English section (50 Qs, 35 min) + review your errors",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "ACT: Online Sample Questions & Practice Tests", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/act-online-test-sample-questions.html" },
      { label: "Mometrix: Free ACT English Practice Test", url: "https://www.mometrix.com/academy/act-english-practice-test/" },
      { label: "Magoosh: Free ACT Practice Test", url: "https://act.magoosh.com/practice_tests/free" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 20,
    date: "May 22",
    isoDate: "2026-05-22",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "Math",
    topic: "Systems of equations + quadratics (FOIL, factoring) — Start with 5 warm-ups",
    resource: "Khan Academy → Systems of equations, Quadratics",
    links: [
      { label: "KA: Systems of Equations", url: "https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:systems-of-equations" },
      { label: "KA: Quadratics — Multiplying & Factoring", url: "https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:quadratics-multiplying-factoring" },
      { label: "KA: Factoring Quadratics (video)", url: "https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:quadratics-multiplying-factoring/x2f8bb11595b61c86:factor-quadratics-intro/v/factoring-quadratic-expressions" },
      { label: "KA: Solving Quadratics by Factoring (practice)", url: "https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:quadratic-functions-equations/x2f8bb11595b61c86:quadratics-solve-factoring/e/solving_quadratics_by_factoring_2" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 21,
    date: "May 23",
    isoDate: "2026-05-23",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "English",
    topic: "Timed drill: 25 grammar-only questions in 15 min",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "Varsity Tutors: ACT English Practice Tests", url: "https://www.varsitytutors.com/act_english-practice-tests" },
      { label: "KA: SAT Grammar Practice (all topics)", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:digital-sat-grammar-practice" },
      { label: "High School Test Prep: ACT English", url: "https://highschooltestprep.com/act/english/" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 22,
    date: "May 24",
    isoDate: "2026-05-24",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "Math",
    topic: "Statistics: mean, median, mode, probability — Start with 5 warm-ups",
    resource: "Khan Academy → Statistics",
    links: [
      { label: "KA: Mean & Median Basics", url: "https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/mean-median-basics" },
      { label: "KA: Mean, Median & Mode Review", url: "https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/mean-median-basics/a/mean-median-and-mode-review" },
      { label: "KA: Basic Probability", url: "https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-probability-statistics/cc-7th-basic-prob" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 23,
    date: "May 25",
    isoDate: "2026-05-25",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "Math",
    topic: "Desmos ACT practice — Start with 5 warm-ups, then apply Desmos to ACT-style problems under timed conditions",
    resource: "Acely ACT Desmos Guide, desmos.com/calculator",
    links: [
      { label: "Desmos Graphing Calculator", url: "https://www.desmos.com/calculator" },
      { label: "Acely: ACT Desmos Guide", url: "https://acely.com/act-prep/act-desmos-calculator" },
      { label: "ACT QuizMe (use with Desmos open)", url: "https://quizme.act.org/" },
      { label: "ACT: Math Calculator How-To Videos", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/math-calculator-how-to-videos.html" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 24,
    date: "May 26",
    isoDate: "2026-05-26",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "English",
    topic: "Your weakest English topics — targeted re-drill based on your errors",
    resource: "Khan Academy + section-strategies.md",
    links: [
      { label: "KA: Grammar Course (all units)", url: "https://www.khanacademy.org/humanities/grammar" },
      { label: "KA: Syntax — SVA, Fragments, Run-ons, Parallelism", url: "https://www.khanacademy.org/humanities/grammar/syntax-conventions-of-standard-english" },
      { label: "KA: Punctuation — Commas & Apostrophes", url: "https://www.khanacademy.org/humanities/grammar/punctuation-the-comma-and-the-apostrophe" },
      { label: "KA: SAT Grammar Practice (all topics)", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:digital-sat-grammar-practice" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 25,
    date: "May 27",
    isoDate: "2026-05-27",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "Math",
    topic: "Backsolving & picking numbers timed practice — 15 ACT-style problems in 20 min",
    resource: "Free Enhanced ACT practice, section-strategies.md",
    links: [
      { label: "ACT QuizMe", url: "https://quizme.act.org/" },
      { label: "Varsity Tutors: ACT Math Practice Tests", url: "https://cdn.varsitytutors.com/act_math-practice-tests" },
      { label: "Magoosh: Backsolving Review", url: "https://act.magoosh.com/lessons/3472-math-strategy-backsolving" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 26,
    date: "May 28",
    isoDate: "2026-05-28",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "English",
    topic: "Full timed English section #2 + review your errors",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "ACT: Online Sample Questions & Practice Tests", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/act-online-test-sample-questions.html" },
      { label: "Quantum ACT Prep: Official Practice Tests", url: "https://quantumactprep.com/actpracticetests" },
      { label: "Union Test Prep: Free ACT Practice", url: "https://uniontestprep.com/act/practice-test" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 27,
    date: "May 29",
    isoDate: "2026-05-29",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "Math",
    topic: "Trig basics: SOH-CAH-TOA (just the fundamentals, 2–3 test questions) — Start with 5 warm-ups",
    resource: "Khan Academy → Trigonometry",
    links: [
      { label: "KA: Intro to Trigonometric Ratios", url: "https://www.khanacademy.org/math/geometry/hs-geo-trig/hs-geo-trig-ratios-intro" },
      { label: "KA: Finding Trig Ratios in Right Triangles (article)", url: "https://www.khanacademy.org/math/geometry/hs-geo-trig/hs-geo-trig-ratios-intro/a/finding-trig-ratios-in-right-triangles" },
      { label: "KA: Trig Ratios (practice)", url: "https://www.khanacademy.org/math/trigonometry/trigonometry-right-triangles/intro-to-the-trig-ratios/e/trigonometry_1" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 28,
    date: "May 30",
    isoDate: "2026-05-30",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "Math",
    topic: "Full timed Math section (45 Qs, 50 min) + review your errors",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "ACT: Online Practice Tests (Enhanced format)", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/act-online-test-sample-questions.html" },
      { label: "Magoosh: Free ACT Practice Test", url: "https://act.magoosh.com/practice_tests/free" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 29,
    date: "May 31",
    isoDate: "2026-05-31",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "Reading",
    topic: "Timed passage practice — focus on inference + vocab-in-context questions",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "ACT: Reading Sample Questions", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/act-online-test-sample-questions.html" },
      { label: "ACT QuizMe", url: "https://quizme.act.org/" },
      { label: "Albert.io: ACT Reading Practice", url: "https://www.albert.io/act-reading/overview" },
      { label: "Albert.io: 12 Must-Know ACT Reading Strategies", url: "https://www.albert.io/blog/12-must-know-act-reading-strategies/" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 30,
    date: "Jun 1",
    isoDate: "2026-06-01",
    phase: 2,
    phaseName: "Strategy + Timed Practice",
    section: "All",
    topic: "Mini-test: 15 English + 15 Math + 9 Reading (timed) — check your progress",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "ACT: Online Sample Questions", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/act-online-test-sample-questions.html" },
      { label: "ACT QuizMe", url: "https://quizme.act.org/" },
      { label: "ACT: Free Practice Test (PDF)", url: "https://www.act.org/content/act/en/students-and-parents/high-school-success/testing-advice-for-the-act/free-act-practice-test.html" },
    ],
    timeMinutes: 45,
  },

  // Phase 3: Full Practice Tests + Final Sharpening (Days 31–41)
  {
    dayNumber: 31,
    date: "Jun 2",
    isoDate: "2026-06-02",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "All",
    topic: "Full practice test — all 3 sections, timed, like the real thing",
    resource: "Official ACT Prep Guide or free Enhanced practice test",
    links: [
      { label: "ACT: Full-Length Enhanced Practice Test", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/act-online-test-sample-questions.html" },
      { label: "ACT: Exam Structure & Timing", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/act-exam-sections-and-structure.html" },
    ],
    timeMinutes: 150,
  },
  {
    dayNumber: 32,
    date: "Jun 3",
    isoDate: "2026-06-03",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "All",
    topic: "Deep review of every wrong answer on your practice test",
    resource: "Your practice test answer key + section-strategies.md",
    links: [
      { label: "SupertutorTV: How to Review ACT Practice Tests", url: "https://supertutortv.com/free-act-prep/" },
    ],
    timeMinutes: 45,
  },
  {
    dayNumber: 33,
    date: "Jun 4",
    isoDate: "2026-06-04",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "All",
    topic: "Targeted drill: your weakest section from the practice test",
    resource: "Khan Academy + section-strategies.md",
    links: [
      { label: "KA: Grammar Course", url: "https://www.khanacademy.org/humanities/grammar" },
      { label: "KA: Pre-Algebra", url: "https://www.khanacademy.org/math/pre-algebra" },
      { label: "KA: Algebra 1", url: "https://www.khanacademy.org/math/algebra" },
      { label: "Fiveable: ACT Reading Hub", url: "https://library.fiveable.me/act/reading" },
    ],
    timeMinutes: 30,
  },
  {
    dayNumber: 34,
    date: "Jun 5",
    isoDate: "2026-06-05",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "All",
    topic: "Targeted drill: your 2nd weakest section + register for July 11 ACT",
    resource: "Khan Academy + act.org/register",
    links: [
      { label: "ACT Registration", url: "https://www.act.org/content/act/en/register-for-the-act.html" },
      { label: "KA: Grammar Course", url: "https://www.khanacademy.org/humanities/grammar" },
      { label: "KA: Pre-Algebra", url: "https://www.khanacademy.org/math/pre-algebra" },
      { label: "KA: Algebra 1", url: "https://www.khanacademy.org/math/algebra" },
    ],
    timeMinutes: 30,
  },
  {
    dayNumber: 35,
    date: "Jun 6",
    isoDate: "2026-06-06",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "English",
    topic: "Rapid-fire grammar drill — 25 questions, 15 min",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "Varsity Tutors: ACT English Practice Tests", url: "https://www.varsitytutors.com/act_english-practice-tests" },
      { label: "KA: SAT Grammar Practice (all topics)", url: "https://www.khanacademy.org/test-prep/sat-reading-and-writing/x0d47bcec73eb6c4b:digital-sat-grammar-practice" },
      { label: "Mometrix: Free ACT English Practice", url: "https://www.mometrix.com/academy/act-english-practice-test/" },
    ],
    timeMinutes: 20,
  },
  {
    dayNumber: 36,
    date: "Jun 7",
    isoDate: "2026-06-07",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "Math",
    topic: "First-30-questions drill — Start with 5 confidence-builder warm-ups, then focus on accuracy with easy/medium questions",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "ACT QuizMe", url: "https://quizme.act.org/" },
      { label: "Varsity Tutors: ACT Math Practice Tests", url: "https://cdn.varsitytutors.com/act_math-practice-tests" },
    ],
    timeMinutes: 30,
  },
  {
    dayNumber: 37,
    date: "Jun 8",
    isoDate: "2026-06-08",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "Reading",
    topic: "1 timed passage — focus on your speed and finding evidence",
    resource: "Free Enhanced ACT practice",
    links: [
      { label: "ACT: Reading Sample Questions", url: "https://www.act.org/content/act/en/products-and-services/the-act/test-preparation/free-act-test-prep/act-online-test-sample-questions.html" },
      { label: "ACT QuizMe", url: "https://quizme.act.org/" },
      { label: "Varsity Tutors: ACT Reading Practice", url: "https://cdn.varsitytutors.com/act_reading-practice-tests" },
    ],
    timeMinutes: 15,
  },
  {
    dayNumber: 38,
    date: "Jun 9",
    isoDate: "2026-06-09",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "All",
    topic: "Review your error patterns — what keeps coming up? Hit those.",
    resource: "Your previous practice test results + section-strategies.md",
    links: [
      { label: "KA: Grammar Course", url: "https://www.khanacademy.org/humanities/grammar" },
      { label: "KA: Pre-Algebra", url: "https://www.khanacademy.org/math/pre-algebra" },
      { label: "ACT QuizMe", url: "https://quizme.act.org/" },
    ],
    timeMinutes: 20,
  },
  {
    dayNumber: 39,
    date: "Jun 10",
    isoDate: "2026-06-10",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "All",
    topic: "Light confidence builder — 10 easy questions per section",
    resource: "Khan Academy or old prep book",
    links: [
      { label: "ACT QuizMe", url: "https://quizme.act.org/" },
      { label: "KA: Grammar Course", url: "https://www.khanacademy.org/humanities/grammar" },
      { label: "KA: Pre-Algebra", url: "https://www.khanacademy.org/math/pre-algebra" },
    ],
    timeMinutes: 15,
  },
  {
    dayNumber: 40,
    date: "Jun 11",
    isoDate: "2026-06-11",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "Rest",
    topic: "REST. No studying. Prepare test-day supplies.",
    resource: "Lay out: photo ID, #2 pencils, calculator, snack, water",
    timeMinutes: 0,
  },
  {
    dayNumber: 41,
    date: "Jun 12",
    isoDate: "2026-06-12",
    phase: 3,
    phaseName: "Full Practice Tests + Final Sharpening",
    section: "Rest",
    topic: "REST. Early bed. Alarm set.",
    resource: "No studying — watch a movie, go for a walk. Bed by 10 PM.",
    timeMinutes: 0,
  },
] as const;

export function getStudyPlanDay(
  dayNumber: number,
): StudyPlanDay | undefined {
  return STUDY_PLAN.find((day) => day.dayNumber === dayNumber);
}
